@extends('layouts.admin')

@section('title', 'Tạo đơn từ yêu cầu')

@section('content')
    <div class="admin-page mx-auto max-w-5xl space-y-5">
        <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-xs font-semibold uppercase tracking-[0.16em] text-rose-500">Xác nhận yêu cầu</p><h1 class="admin-page-title mt-1">Tạo đơn từ {{ $customOrderRequest->request_code }}</h1><p class="admin-page-subtitle">Chọn sản phẩm thật, xác nhận giá và thông tin đơn trước khi tạo.</p></div><x-admin.button :href="route('admin.custom-orders.show', $customOrderRequest)" variant="secondary">Quay lại yêu cầu</x-admin.button></div>
        <form method="POST" action="{{ route('admin.custom-orders.create-order.store', $customOrderRequest) }}" class="grid gap-5 lg:grid-cols-3">@csrf
            <section class="admin-panel admin-panel--padded space-y-5 lg:col-span-2"><div><h2 class="text-base font-bold text-gray-900">Sản phẩm và giá</h2><p class="mt-1 text-xs text-gray-500">`order_items.product_id` bắt buộc phải là sản phẩm có thật.</p></div><div><label class="text-sm font-semibold text-gray-700" for="product_id">Sản phẩm <span class="text-rose-600">*</span></label><select id="product_id" name="product_id" required class="mt-1.5 w-full rounded-lg border border-gray-200 px-3 py-2.5 text-sm"><option value="">Chọn sản phẩm</option>@foreach ($products as $product)<option value="{{ $product->id }}" data-price="{{ $product->sale_price && $product->sale_price < $product->price ? $product->sale_price : $product->price }}" @selected((string) old('product_id') === (string) $product->id)>{{ $product->name }} · Tồn {{ $product->stock }}</option>@endforeach</select></div><div class="grid gap-4 sm:grid-cols-2"><div><label class="text-sm font-semibold text-gray-700" for="quantity">Số lượng <span class="text-rose-600">*</span></label><input id="quantity" name="quantity" type="number" min="1" required value="{{ old('quantity', $customOrderRequest->quantity ?: 1) }}" class="mt-1.5 w-full rounded-lg border border-gray-200 px-3 py-2.5 text-sm"></div><div><label class="text-sm font-semibold text-gray-700" for="unit_price">Đơn giá <span class="text-rose-600">*</span></label><input id="unit_price" name="unit_price" type="number" min="0" step="1000" required value="{{ old('unit_price') }}" class="mt-1.5 w-full rounded-lg border border-gray-200 px-3 py-2.5 text-sm"></div></div><div class="grid gap-4 sm:grid-cols-2"><div><label class="text-sm font-semibold text-gray-700" for="shipping_fee">Phí giao hàng</label><input id="shipping_fee" name="shipping_fee" type="number" min="0" step="1000" value="{{ old('shipping_fee', 0) }}" class="mt-1.5 w-full rounded-lg border border-gray-200 px-3 py-2.5 text-sm"></div><div><label class="text-sm font-semibold text-gray-700" for="discount">Giảm giá</label><input id="discount" name="discount" type="number" min="0" step="1000" value="{{ old('discount', 0) }}" class="mt-1.5 w-full rounded-lg border border-gray-200 px-3 py-2.5 text-sm"></div></div><p class="rounded-lg bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-800">Tổng dự kiến: <span id="estimated_total">0₫</span></p></section>
            <aside class="space-y-5"><section class="admin-panel admin-panel--padded space-y-4"><h2 class="text-base font-bold text-gray-900">Giao hàng & thanh toán</h2><div><label class="text-sm font-semibold text-gray-700" for="recipient_name">Người nhận</label><input id="recipient_name" name="recipient_name" required value="{{ old('recipient_name', $customOrderRequest->customer_name) }}" class="mt-1.5 w-full rounded-lg border border-gray-200 px-3 py-2.5 text-sm"></div><div><label class="text-sm font-semibold text-gray-700" for="recipient_phone">Số điện thoại</label><input id="recipient_phone" name="recipient_phone" required value="{{ old('recipient_phone', $customOrderRequest->phone) }}" class="mt-1.5 w-full rounded-lg border border-gray-200 px-3 py-2.5 text-sm"></div><div><label class="text-sm font-semibold text-gray-700" for="delivery_date">Ngày giao</label><input id="delivery_date" name="delivery_date" type="date" min="{{ now()->toDateString() }}" required value="{{ old('delivery_date', $customOrderRequest->delivery_date?->format('Y-m-d')) }}" class="mt-1.5 w-full rounded-lg border border-gray-200 px-3 py-2.5 text-sm"></div><div><label class="text-sm font-semibold text-gray-700" for="delivery_slot_id">Khung giờ giao</label><select id="delivery_slot_id" name="delivery_slot_id" class="mt-1.5 w-full rounded-lg border border-gray-200 px-3 py-2.5 text-sm"><option value="">Chưa chọn</option>@foreach($deliverySlots as $slot)<option value="{{ $slot->id }}" @selected((string) old('delivery_slot_id') === (string) $slot->id)>{{ $slot->name }}</option>@endforeach</select></div><div><label class="text-sm font-semibold text-gray-700" for="payment_method">Phương thức thanh toán</label><select id="payment_method" name="payment_method" class="mt-1.5 w-full rounded-lg border border-gray-200 px-3 py-2.5 text-sm"><option value="cod" @selected(old('payment_method', 'cod') === 'cod')>COD</option><option value="paypal" @selected(old('payment_method') === 'paypal')>PayPal (chưa thu tiền)</option></select></div></section></aside>
            <section class="admin-panel admin-panel--padded space-y-4 lg:col-span-3"><div><label class="text-sm font-semibold text-gray-700" for="recipient_address">Địa chỉ giao <span class="text-rose-600">*</span></label><textarea id="recipient_address" name="recipient_address" required rows="2" class="mt-1.5 w-full rounded-lg border border-gray-200 px-3 py-2.5 text-sm">{{ old('recipient_address', $customOrderRequest->delivery_address) }}</textarea></div><div><label class="text-sm font-semibold text-gray-700" for="order_note">Ghi chú đơn hàng</label><textarea id="order_note" name="order_note" rows="3" class="mt-1.5 w-full rounded-lg border border-gray-200 px-3 py-2.5 text-sm">{{ old('order_note', $customOrderRequest->admin_note) }}</textarea></div><div class="flex justify-end"><x-admin.button type="submit" variant="primary">Xác nhận & tạo đơn</x-admin.button></div></section>
        </form>
    </div>
    <script>const money=(value)=>new Intl.NumberFormat('vi-VN').format(Math.max(0,value||0))+'₫';const updateTotal=()=>{const quantity=Number(document.getElementById('quantity').value)||0;const price=Number(document.getElementById('unit_price').value)||0;const shipping=Number(document.getElementById('shipping_fee').value)||0;const discount=Number(document.getElementById('discount').value)||0;document.getElementById('estimated_total').textContent=money((quantity*price)+shipping-discount)};['quantity','unit_price','shipping_fee','discount'].forEach((id)=>document.getElementById(id).addEventListener('input',updateTotal));document.getElementById('product_id').addEventListener('change',(event)=>{const price=event.target.selectedOptions[0]?.dataset.price;if(price&&!document.getElementById('unit_price').value){document.getElementById('unit_price').value=price}updateTotal()});updateTotal();</script>
@endsection
