@extends('layouts.admin')

@section('title', 'Chi tiết yêu cầu đặt hoa')

@section('content')
    @php($status = $customOrderRequest->status)
    <div class="admin-page mx-auto max-w-6xl space-y-5">
        <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-xs font-semibold uppercase tracking-[0.16em] text-rose-500">Yêu cầu đặt hoa</p><h1 class="admin-page-title mt-1">{{ $customOrderRequest->request_code }}</h1><p class="admin-page-subtitle">Gửi lúc {{ $customOrderRequest->created_at->format('d/m/Y H:i') }} · {{ $customOrderRequest->user_id ? 'Khách hàng thành viên' : 'Khách vãng lai' }}</p></div><x-admin.button :href="route('admin.custom-orders.index')" variant="secondary"><svg aria-hidden="true" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m11.5 15-5-5 5-5" stroke-linecap="round" stroke-linejoin="round" /></svg>Quay lại</x-admin.button></div>

        <div class="grid gap-5 xl:grid-cols-3">
            <section class="admin-panel admin-panel--padded xl:col-span-2"><div class="mb-5 flex flex-wrap items-start justify-between gap-3 border-b border-rose-50 pb-4"><div><h2 class="text-base font-bold text-gray-900">Thông tin khách & yêu cầu</h2><p class="mt-1 text-xs text-gray-500">{{ $customOrderRequest->user_id ? 'Tài khoản: ' . ($customOrderRequest->user?->name ?? '—') . ' · ' . ($customOrderRequest->user?->email ?? '—') : 'Khách chưa đăng nhập' }}</p></div><x-admin.status-badge :status="$status" type="custom-order" /></div>
                <dl class="grid grid-cols-1 gap-3 sm:grid-cols-2"><div class="rounded-xl border border-gray-100 bg-gray-50/70 p-4"><dt class="text-xs font-semibold text-gray-500">Họ tên</dt><dd class="mt-1 text-sm font-semibold text-gray-900">{{ $customOrderRequest->customer_name }}</dd></div><div class="rounded-xl border border-gray-100 bg-gray-50/70 p-4"><dt class="text-xs font-semibold text-gray-500">Số điện thoại</dt><dd class="mt-1 text-sm font-semibold text-gray-900">{{ $customOrderRequest->phone }}</dd></div><div class="rounded-xl border border-gray-100 bg-gray-50/70 p-4"><dt class="text-xs font-semibold text-gray-500">Email</dt><dd class="mt-1 text-sm font-semibold text-gray-900">{{ $customOrderRequest->email ?: '—' }}</dd></div><div class="rounded-xl border border-gray-100 bg-gray-50/70 p-4"><dt class="text-xs font-semibold text-gray-500">Dịp tặng</dt><dd class="mt-1 text-sm font-semibold text-gray-900">{{ $customOrderRequest->occasion ?: '—' }}</dd></div><div class="rounded-xl border border-gray-100 bg-gray-50/70 p-4"><dt class="text-xs font-semibold text-gray-500">Loại hoa / số lượng</dt><dd class="mt-1 text-sm font-semibold text-gray-900">{{ $customOrderRequest->flower_type ?: '—' }} · {{ $customOrderRequest->quantity ?: '—' }}</dd></div><div class="rounded-xl border border-gray-100 bg-gray-50/70 p-4"><dt class="text-xs font-semibold text-gray-500">Ngân sách / ngày giao</dt><dd class="mt-1 text-sm font-semibold text-gray-900">{{ $customOrderRequest->budget !== null ? number_format($customOrderRequest->budget, 0, ',', '.') . '₫' : '—' }} · {{ $customOrderRequest->delivery_date?->format('d/m/Y') ?? '—' }}</dd></div><div class="rounded-xl border border-gray-100 bg-gray-50/70 p-4 sm:col-span-2"><dt class="text-xs font-semibold text-gray-500">Địa chỉ giao</dt><dd class="mt-1 text-sm font-semibold leading-6 text-gray-900">{{ $customOrderRequest->delivery_address ?: '—' }}</dd></div><div class="rounded-xl border border-gray-100 bg-gray-50/70 p-4 sm:col-span-2"><dt class="text-xs font-semibold text-gray-500">Nội dung yêu cầu</dt><dd class="mt-1 whitespace-pre-line text-sm font-semibold leading-6 text-gray-900">{{ $customOrderRequest->message ?: '—' }}</dd></div></dl>
            </section>

            <aside class="space-y-5"><section class="admin-panel admin-panel--padded"><h2 class="text-base font-bold text-gray-900">Liên hệ & xử lý</h2><div class="mt-4 flex flex-col gap-2"><a href="tel:{{ $customOrderRequest->phone }}" class="admin-button admin-button--secondary admin-button--md"><svg aria-hidden="true" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M6.5 2.8 9 5.3 7.4 7.6a11.5 11.5 0 0 0 5 5l2.3-1.6 2.5 2.5-1.4 2.3c-.5.8-1.5 1.2-2.4.9A15.4 15.4 0 0 1 3.3 6.6c-.3-.9.1-1.9.9-2.4l2.3-1.4Z" stroke-linecap="round" stroke-linejoin="round" /></svg>Gọi khách</a>
                @if (in_array($status, ['pending', 'contacted'], true))<form method="POST" action="{{ route('admin.custom-orders.contacted', $customOrderRequest) }}">@csrf @method('PATCH')<x-admin.button type="submit" variant="secondary" class="w-full">Đã liên hệ</x-admin.button></form>@endif
                @if ($status === 'accepted')<x-admin.button :href="route('admin.custom-orders.create-order', $customOrderRequest)" variant="primary" class="w-full">Xác nhận & tạo đơn</x-admin.button>@endif
                @if ($status === 'converted' && $customOrderRequest->order)<x-admin.button :href="route('admin.orders.show', $customOrderRequest->order)" variant="detail" class="w-full">Xem đơn hàng</x-admin.button>@endif
            </div></section>
            @if (in_array($status, ['pending', 'contacted', 'accepted'], true))<section class="admin-panel admin-panel--padded"><h2 class="text-base font-bold text-gray-900">Nhận yêu cầu</h2><form method="POST" action="{{ route('admin.custom-orders.accept', $customOrderRequest) }}" class="mt-4 space-y-3">@csrf @method('PATCH')<textarea name="admin_note" rows="4" class="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm" placeholder="Ghi chú gửi khách hoặc nội bộ...">{{ old('admin_note', $customOrderRequest->admin_note) }}</textarea><x-admin.button type="submit" variant="primary" class="w-full">Nhận yêu cầu</x-admin.button></form></section>@endif
            @if ($status !== 'converted')<section class="admin-panel admin-panel--padded"><h2 class="text-base font-bold text-gray-900">Từ chối yêu cầu</h2><form method="POST" action="{{ route('admin.custom-orders.reject', $customOrderRequest) }}" class="mt-4 space-y-3">@csrf @method('PATCH')<textarea name="rejection_reason" rows="4" required class="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm" placeholder="Lý do từ chối (bắt buộc)">{{ old('rejection_reason', $customOrderRequest->rejection_reason) }}</textarea><x-admin.button type="submit" variant="danger" class="w-full">Từ chối</x-admin.button></form></section>@endif
            </aside>
        </div>
    </div>
@endsection
